networks:
  shared:
    external: true
    name: proxy-bridge 

services:
  medhack-frontend:
    container_name: medhack-frontend
    image: caillinnugent/medhack-frontend:${FRONTEND_TAG}
    networks:
     - shared
   restart: unless-stopped
