networks:
  shared:
    external: true
    name: proxy-bridge 

services:
  personal-site:
    container_name: bluesfest-site
    image: caillinnugent/bluesfest:latest
    networks:
      - shared
    restart: unless-stopped
