# postgres

server {
    listen 5432;
    proxy_pass postgres:5432;
}

# bittorrent proxy

server {
    listen 6881;
    resolver 127.0.0.11;
	set $upstream qbittorrent:6881;
    proxy_pass $upstream;
}
