
server {
    listen 3306;
    resolver 127.0.0.11 valid 30s;
    set $upstream medhack-frontiers-db-staging:3306;
    proxy_pass $upstream;

    proxy_connect_timeout 30s;
    proxy_timeout 10m;
}

# bittorrent proxy

server {
    listen 6881;
    resolver 127.0.0.11 valid 30s;
	set $upstream qbittorrent:6881;
    proxy_pass $upstream;
}
