# postgres
map $ssl_preread_server_name $target_backend {
    db.develop.visitor_count.caillin.dev postgres:5432;
}

server {
    listen 5432;
    proxy_pass $target_backend;
    ssl_preread on;
}

# bittorrent proxy

server {
    listen 6881;
    resolver 127.0.0.11;
	set $upstream qbittorrent:6881;
    proxy_pass $upstream;
}
