networks:
  shared:
    external: true
    name: proxy-bridge 
services:
  postgres:
    image: postgres:18
    container_name: postgres
    env_file: "postgres.env"
    volumes:
    - postgres_data:/var/lib/postgresql
    networks:
     - shared 
volumes:
  postgres_data:
