networks:
  shared:
    external: true
    name: proxy-bridge 
services:
  admin-frontend:
    image: registry.gitlab.com/ncaillin/terrain_admin_frontend:latest
    container_name: terrain_admin_frontend
    volumes:
      - ./.admin_frontend_env:/app/.env
    restart: 'unless-stopped'
    networks:
     - shared 
  spring-backend:
    image: registry.gitlab.com/ncaillin/terrain_backend:latest
    container_name: terrain_backend
    env_file:
      - backend_docker.env
    volumes:
      - ./.backend_env:/app/.env
    restart: 'unless-stopped'
    networks:
     - shared 
  