name: Push repository to Remote Server
on: [push, workflow_dispatch]
jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - uses: nugentcaillin/actions/cloudflared-ssh@main
        with:
          id: ${{secrets.CF_ACCESS_CLIENT_ID}}
          secret: ${{secrets.CF_ACCESS_CLIENT_SECRET}}
          key: ${{secrets.DEPLOY_BOT_PRIVATE_KEY}}
          user: ${{secrets.DEPLOY_BOT_USER}}
          host: ${{secrets.DEPLOY_BOT_HOST}}
          script: |
            cd /opt/infra/homelab-orchestration
            git pull 
            docker compose pull  
            docker compose up -d --remove-orphans
            docker exec reverse-proxy nginx -s reload
