name: test ssh cloudflared action
on: workflow_dispatch
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: nugentcaillin/actions/cloudflared-ssh@main
        with:
          id: ${{secrets.CF_ACCESS_CLIENT_ID}}
          secret: ${{secrets.CF_ACCESS_CLIENT_SECRED}}
          key: ${{secrets.DEPLOY_BOT_PRIVATE_KEY}}
          user: ${{secrets.DEPLOY_BOT_USER}}
          host: ${{secrets.DEPLOY_BOT_HOST}}
          script: |
            echo "hello from $(hostname)"
            ls -la

