name: Update medhack backend
on: 
  repository_dispatch:
    types: [update-backend]
jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - uses: nugentcaillin/actions/cloudflared-ssh@main
        with:
          id: ${{secrets.CF_ACCESS_CLIENT_ID}}
          secret: ${{secrets.CF_ACCESS_CLIENT_SECRET}}
          key: ${{secrets.DEPLOY_BOT_PRIVATE_KEY}}
          user: ${{secrets.DEPLOY_BOT_USER}}
          host: ${{secrets.DEPLOY_BOT_HOST}}
          script: |
            cd /opt/infra/homelab-orchestration
            sed -i "s/^BACKEND_TAG=.*/BACKEND_TAG=${{ github.event.client_payload.new_tag }}/" .env
            docker compose pull medhack-backend
            docker compose up -d medhack-backend
            docker image prune -f
